import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from 'next/headers';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const country = headersList.get('x-country') || 'US';
  const currency = country === 'IN' ? '₹' : '$';
  const lang = country === 'IN' ? 'hi' : 'en';

  return (
    <html lang={lang}>
      <body>
        <header>
          <h1>🌍 GeoFuse</h1>
          <p>Country: {country}</p>
          <p>Currency: {currency}</p>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );

}

