import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from 'next/headers';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await  headers();
  for (const [key, value] of headersList.entries()) {
    console.log('heres the header list',`${key}: ${value}`);
  }
  const referer = headersList.get('referer') || 'http://localhost:3000';
  const url = new URL(referer);

  const queryCountry = url.searchParams.get('country') || 'US';
  
  console.log('queryCountry', queryCountry)

  
  const headerCountry = headersList.get('x-country') || 'US';
  console.log('headerCountry', headerCountry)
  const country = queryCountry || headerCountry;


 const isIndia = country === 'IN';
  const currency = isIndia ? '₹' : '$';
  const lang = isIndia ? 'hi' : 'en';
  const greeting = isIndia ? 'नमस्ते!' : 'Hello!';
  const price = isIndia ? '₹999' : '$9.99';

  return (
    <html lang={lang}>
      <body className="p-6">
        <header className="mb-4">
          <h1 className="text-2xl font-bold">🌍 GeoFuse</h1>
          <p>Country: {country}</p>
          <p>Greeting: {greeting}</p>
          <p>Price: {price}</p>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );

}

